### ISSUE TITLE
Function duct: Add argument phi

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#1]
# Function duct: Argument phi

1. remove the argument "new": it is not needed anymore;
2. add the argument phi = c(0,0);
   - it specifies the rotation of the 2 circles;

## Code:

   duct = function(n, R = c(5, 7), nc.r=1/2, center=c(0,0), nc.fill = "#E03232", phi=c(0,0)) {
   if(length(phi) == 1) phi = c(phi, phi);
   c1 = pointsCircle(n, r=R[1], center=center, phi=phi[1]);
   c2 = pointsCircle(n, r=R[2], center=center, phi=phi[2]);

## Example:

   n = c(20, 15)
   plot.base(xlim=c(-20,20), ylim=c(-20,20))
   lines(duct(n[1], c(15,18), phi=pi/2/n[1]))
   lines(duct(n[1], c(9,13), phi=c(0, pi/n[2])))
   abline(h=0, col="green")

**Comment by Adi131313** [comment]
issue fixed
