### ISSUE TITLE
Circular Helix

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#11]
# Function to draw Circular Helix

Note:
- will be useful to draw the cDNA or cRNA in viruses;

## R Code

	helix.rad = function(R=3, n=8, center=c(0,0), r=1, phi=0, N=257) {	
		id = seq(0, 1, length.out = N)
		rr = r * cos(2*pi*n*id + phi);
		RR = exp(2i*pi*id);
		RR = R*RR + rr*RR;
		x  = Re(RR) + center[1];
		y  = Im(RR) + center[2];
		xy = list(x=x, y=y);
		class(xy) = c("polygon", "list");
		xy = list(xy);
		class(xy) = "bioshape";
		return(xy);
	}

### Circular Helix
	R = 5; n = 20;
	lim = c(-R, R) + c(-1,1);
	plot.base(xlim = lim, ylim = lim)
	xy = helix.rad(R=R, n=n, N=512)
	lines(xy)
	xy = helix.rad(R=R, n=n, phi=pi/2, N=512)
	lines(xy, col="red")

	### Flower 1:
	R = 5; n = 11;
	lim = c(-R, R) + c(-2,2);
	plot.base(xlim = lim, ylim = lim)
	xy = helix.rad(R=R, n=n, phi=pi)
	lines(xy)
	xy = helix.rad(R = R - 1, n=n, phi=pi)
	lines(xy, col="red")

	### Flower 2:
	R = 5; n = 11;
	lim = c(-R, R)*2 + c(-1,1);
	plot.base(xlim = lim, ylim = lim)
	xy = helix.rad(R=R, r=R, n=n, N=256)
	lines(xy, col="red")

	### Other
	R = 5; n = 10;
	lim = c(-R, R) + c(-2,2);
	plot.base(xlim = lim, ylim = lim)
	abline(h=0, col="green", lty=2)
	for(r in c(3,4,6,9)) {
		xy = helix.rad(R = R - 2/r, n=n, phi=pi, r = 2/r);
		lines(xy, col="red");
	}

**Comment by Adi131313** [comment]
issue fixed
