### ISSUE TITLE
Updated Function plot.base

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#14]
# Updated Function plot.base

- new argument: asp = 1;
- the function is in file: Graphic.Helper.Plot.R;

## R Code

	plot.base = function(xlim=c(-2,10), ylim=c(-2,10), axt=c(1,2), asp=1, set.par=TRUE) {
		hasAxis = ! is.null(axt);
		if(set.par) {
			mar = 0.25 + if(hasAxis) c(2,2,0,0) else c(0,0,0,0);
			par.old = par(mar = mar);
		} else par.old = NA;
		plot.new()
		plot.window(xlim=xlim, ylim=ylim, asp=asp)
		if(hasAxis) {
			lapply(axt, function(a) axis(a));
		}
		invisible(par.old);
	}

**Comment by Adi131313** [comment]
issue fixed
