### ISSUE TITLE
New Function: circle.ngon

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#15]
# New Function: circle.ngon

The function draws ngons radially to form a circle of specified radius.

## R Code
	circle.ngon = function(R=3, center=c(0,0), r=1/4, n=3, phi=0, clockwise=TRUE,
			r.adj = -0.01, phi.adj=0) {
		if(n %% 2 == 0) { d = 2; }
		else d = (1 + cos(pi/n));
		# ng = number of ngons;
		th = acos(1 - (d*r/R)^2);
		ng = round(2*pi / th);
		shift = function(x) (x + c(x[-1], x[1])) / 2;
		th = 2*pi*seq(0, ng) / ng + phi;
		px = R * cos(th) + center[1];
		py = R * sin(th) + center[2];
		# Note: contact points are on the circle R;
		cx = shift(px);
		cy = shift(py);
		# corrected r:
		r  = sqrt((px[1] - cx[1])^2 + (py[1] - cy[1])^2) + r.adj;
		r  = 2*r / d;
		t0 = if(clockwise) 3*pi/2 else pi/2;
		th = t0 + th + pi/ng + phi.adj;
		pg = lapply(seq(ng), function(id) {
			ngon(n, r=r, center=c(cx[id], cy[id]), phi = th[id]);
		})
		attr(pg, "r") = r;
		class(pg) = "bioshape";
		return(pg);
	}

## Examples
Note: slightly parametrized the example function;

	examples.GonsOnCircle = function(R = 3, ngons = c(3,4,5,6)) {
		par.old = par(mfrow = c(2,2))
		lim = R + 1; lim = c(-lim, lim);
		# Plot 1:
		n = ngons[1];
		plot.base(xlim=lim, ylim=lim, axt=NULL)
		ng = circle.ngon(R=R, n=n)
		lines(ng, fill=3)
		ng = circle.ngon(R = R - 1, n=n, clockwise = FALSE)
		lines(ng, fill=4)
		# Plot 2:
		n = ngons[2];
		plot.base(xlim=lim, ylim=lim, axt=NULL)
		ng = circle.ngon(R=R, n=n)
		lines(ng)
		ng = circle.ngon(R = R - 1, n=n, phi = pi/20)
		lines(ng)
		# Plot 3:
		n = ngons[3];
		plot.base(xlim=lim, ylim=lim, axt=NULL)
		ng = circle.ngon(R=R, n=n)
		lines(ng, fill=5)
		# Plot 4:
		n = ngons[4];
		plot.base(xlim=lim, ylim=lim, axt=NULL)
		ng = circle.ngon(R=R, n=n)
		lines(ng)
		
		par(par.old);
		invisible();
	}

**Comment by Adi131313** [comment]
issue fixed
