### ISSUE TITLE
Function: plot.circle

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#16]
# Function: plot.circle

This function removes partly the dependency on package shape (enabling to abstract the use of plotcircle from package shape).
- add function in file: Graphic.Helper.Plot.R;

## R Code

	plot.circle = function(r, center=c(0,0), col=1, fill=NULL, N=128, ...) {
		x = r * cos(2*pi*seq(0, N-1) / N);
		y = r * sin(2*pi*seq(0, N-1) / N);
		polygon(x, y, border=col, col=fill, ...);
		invisible();
	}

**Comment by Adi131313** [comment]
issue fixed
