### ISSUE TITLE
Function shiftLine: new argument id.offset = 0

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#19]
# Function shiftLine: add argument id.offset

The function is in file: Graphic.Helper.R; will discuss the details during next meeting.

## R Code
	shiftLine = function(x, y, d=1, slope=NULL, scale=1, id.offset=0) {
		...; # changes of type: id = id + id.offset
	}

**Comment by Adi131313** [comment]
issue fixed
