### ISSUE TITLE
Correct Angles for Convex Lens

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#21]
# Correct Angles for Convex Lens

This is a follow-up issue to the Convex Lens. Includes code to compute correctly the angles of the circle segments.

### Convex lens
	#' @export
	lens = function(x, y, R = NULL, scale = c(1,1),
        	        lwd=1, col=1) {
		d2 = (x[2] - x[1])^2 + (y[2] - y[1])^2;
		d  = sqrt(d2);
		### Lens Radius
		if(is.null(R)) {
			R = d;
			R = c(R, R);
		} else if(length(R) == 1) R = c(R, R);
		R = R * scale;
		
		### Center of Base
		mid.x = (x[1] + x[2]) / 2;
		mid.y = (y[1] + y[2]) / 2;

		### Step 3
		dc = R^2 - d2/4;
		if(any(dc < 0)) stop("Invalid Lens Radius: too small!");
		dc = sqrt(dc) * sign(R);
		# TODO: Proper sign of d1 and d2
		d1 = dc[1];
		d2 = - dc[2];
	
		# Step 4: Circle Centers
		slope = slope(x, y);
		c1 = shiftLine(mid.x, mid.y, slope = slope, d = d1);
		c2 = shiftLine(mid.x, mid.y, slope = slope, d = d2);
	
		# Step 5: Circle Segments
		R = abs(R);
		alpha = asin(d/(2*R));
		phi1 = atan2((mid.y - c1$y), (mid.x - c1$x));
		phi2 = atan2((mid.y - c2$y), (mid.x - c2$x));
		clock = - c(-1,1);
		phi1 = phi1 + clock*alpha[1];
		phi2 = phi2 + clock*alpha[2];
		phi1 = rev(phi1);
		phi2 = rev(phi2);
	
		# TODO: handle data.frame?
		c1 = unlist(c1[1, c(1, 2)]);
		c2 = unlist(c2[1, c(1, 2)]);
		lst1 = list(r = R[1], center = c1, phi = phi1);
		lst2 = list(r = R[2], center = c2, phi = phi2);
		class(lst1) = c("circle.arc", "list");
		class(lst2) = c("circle.arc", "list");
	
		lst = list(lst1, lst2);
		class(lst) = c("bioshape", "list");
		return(lst);
	}

**Comment by Adi131313** [comment]
issue fixed
