### ISSUE TITLE
[Fix] Star with Circular Arcs (Neuron)

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#23]
# Neuron / Star with Circular Arcs

- fix for the initial rotation;
- function name: was renamed to neuron.body (although it is not yet the final name);

### Star with Circular Arcs
	#' @export
	neuron.body = function(center = c(0, 0), n = 5, r = 3, phi = 0){
		phi0 = phi + pi/n;
		cc = circlesOnFixedCircle(n = n, r = r, center = center, phi = phi0);
		R = r;
		r = attr(cc, "r");
		phin = 2*pi/n;
		id = seq(n);
		a1 = pi/2 + phi + id * phin;
		a2 = pi/2 + phi + (id + (n - 2)/2) * phin;
		lst = lapply(id, function(id){
			lst = list(
				r = r, center = c(x = cc$x[id], y = cc$y[id]),
				phi = c(a1[id], a2[id]) );
			class(lst) = c("circle.arc", "list");
			return(lst);
		})
		attr(lst, "r") = r;
		class(lst) = c("bioshape", "list");
		return(lst);
	}

**Comment by Adi131313** [comment]
issue fixed
