### ISSUE TITLE
Function to draw Neuron

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#24]
# FUnction neuron

Updated version of the function:
- the function was also renamed to neuron, while the base-function was renamed neuron.body (see previous issue);
- includes also the nucleus;

### Neuron
	#' @export
	neuron = function(center = c(0, 0), n = 5, r = 2, phi = 0,
				axon.length = 3 * r, dendrite.length = ~ r/2, r.nucl = ~ (R - r)/2,
				col.nucl = 1, fill.nucl = NULL) {
		body = neuron.body(center = center, n = n, r = r, phi = phi);
		### Init
		axon.length = axon.length; # force = scale * r;
		R = r;
		r = attr(body, "r");
		phin = 2 * pi/n;
		phi0 = - phin/2;
		pi20 = pi/2; pi32 = 3*pi/2;
		phiD = seq(n) * phin + phi;
		phiR = phiD - (2*pi) * floor(phiD / (2*pi));
		x0 = r * cos(phiD + pi20) + R * cos(phiD + phi0);
		y0 = r * sin(phiD + pi20) + R * sin(phiD + phi0);
		x0 = x0 + center[1];
		y0 = y0 + center[2];
		sg = ifelse(phiR > pi/2 & phiR <= pi32, - 1, 1);
		### Axon
		if(axon.length != 0) {
			xy = shiftPoint(c(x0[n], y0[n]), d = sg[n] * axon.length, slope = tan(phiD[n]));
			axon = list(x = c(x0[n], xy[1]), y = c(y0[n], xy[2]));
			axon = list(axon);
			lenDendites = n - 1;
		} else {
			axon = NULL;
			lenDendites = n;
		}
		### Dendrites
		eval.formula = function(x) {
			xx = if(inherits(x, "formula")) {
				eval(x[[2]]);
			} else x;
		}
		dendrite.len = eval.formula(dendrite.length);
		dendrite.len = sg * dendrite.len;
		dend = lapply(seq(lenDendites), function(k) {
			tree(c(x0[k], y0[k]), d = dendrite.len[k], slope = tan(phiD[k]),
				n = 2, levels = 2); # TODO
		})
		### Nucleus
		r.nucl = eval.formula(r.nucl);
		if(r.nucl > 0) {
			nucleus = list(r = r.nucl, center = center, col = col.nucl, fill = fill.nucl);
			class(nucleus) = c("circle", "list");
			nucleus = list(nucleus);
		} else nucleus = NULL;
		### Neuron
		neuron = c(body, axon, dend, nucleus);
		if( ! inherits(neuron, "bioshape")) {
			class(neuron) = c("bioshape", "list");
		}
		return(neuron);
	}
	#' @export
	tree = function(p, d, slope, n=2, levels=2) {
		xy = shiftPoint(p, d=d, slope = slope);
		xy = list(x = c(p[1], xy[1]), y = c(p[2], xy[2]));
		return(xy);
	}

**Comment by discoleo** [comment]
## Tests & Examples

Note:
- you will need to write a proper test suite for this function;

### R Code
	###
	phi = 0;
	n = 5;
	center = c(2, 3)
	plot.base()
	tmp = neuron(n = n, center = center, phi = phi)
	lines(tmp)
	
	###
	phi = -pi/2;
	n = 5;
	center = c(2, 3)
	plot.base()
	tmp = neuron(n = n, center = center, phi = phi)
	lines(tmp)
	
	###
	phi = 2*pi - pi/2;
	n = 5;
	center = c(2, 3)
	plot.base()
	tmp = neuron(n = n, center = center, phi = phi)
	lines(tmp)
	
	###
	phi = pi/2;
	n = 5;
	center = c(2, 3)
	plot.base()
	tmp = neuron(n = n, center = center, phi = phi)
	lines(tmp)
	
	###
	phi = 2*pi - pi/6;
	n = 5;
	center = c(2, 3)
	plot.base()
	tmp = neuron(n = n, center = center, phi = phi)
	lines(tmp)

**Comment by Adi131313** [comment]
issue fixed
