### ISSUE TITLE
[Examples] Move Function all_arrows to new file: Examples.Arrows.R

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#25]
# Move Function all_arrows to new file

Move the function **all_arrows** from tests/Examples.R to new file:
> R/examples.Arrows.R

Rename also the function to **examples.arrows**.

## R Code
- extract also lwd as an argument of the function;

	examples.arrows = function(new.plot = TRUE, lwd = 2) {
		### Plot
		if(new.plot) plot.base();
		# ...

**Comment by Adi131313** [comment]
issue fixed
