### ISSUE TITLE
Grouped Lenses

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#31]
# Function to Generate Group of Lenses

The group of lenses is aligned on the same optical axes.

## R Code

	# x, y = endpoints of Axis (group of lens);
	lens.group = function(x, y, h, pos=NULL, R=NULL, l.scale=1,
			lwd=1, col=1, fill=NULL, lty=1) {
		len = length(h);
		if(is.null(pos)) {
			if(len > 2) stop("Specify the position of all the lenses!");
			pos = c(0, 1);
		}
		slope = slope(x, y);
		### Lens Positions
		xL = (1 - pos)*x[1] + pos*x[2];
		yL = (1 - pos)*y[1] + pos*y[2];
		#
		isR = ! is.null(R);
		lst = lapply(seq(len), function(id) {
			d  = h[id]; d = c(-d, d);
			xy = shiftLine(xL[id], yL[id], slope=slope, d=d);
			R  = if(isR) R[id] else NULL;
			scR = if(length(l.scale) == 1) l.scale else l.scale[id];
			lwd = if(length(lwd) == 1) lwd else lwd[id];
			col = if(length(col) == 1) col else col[id];
			lst = lens(xy$x, xy$y, R=R, scale=scR, lwd=lwd, col=col);
			lty = if(length(lty) == 1) lty else lty[id];
			lst[[1]]$lty = lty;
			lst[[2]]$lty = lty;
			if( ! is.null(fill)) {
				fill = if(length(fill) == 1) fill else fill[id];
				lst[[1]]$fill = fill;
				lst[[2]]$fill = fill;
			}
			return(lst);
		});
		lst = do.call(c, lst);
		return(as.bioshape(lst));
	}

### Example: Lens Group
	pos = c(0, 1/3, 1)
	h = c(1, 1.2, 1.5)
	scale.R = c(1, 1.5, 2)
	x = c(0, 6); y = c(0, 4);
	# fill: does NOT work with concave lenses;
	fill = "#6480D0";
	#
	lst = lens.group(x=x, y=y, h=h, pos=pos, l.scale = scale.R, fill=fill)
	plot.base()
	lines(lst)
	lines(x, y, lty=2, lwd=2, col="green")

**Comment by Adi131313** [comment]
issue implemented
