### ISSUE TITLE
[Graphic.Objects.Spirals.R] Fixes for Function helix

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#32]
# Function helix

Various fixes.

1.) Keep value of n
- we need to preserve the value of n on line 66;
	npi  = 2*n*pi;
	ninv = 1 / npi;
	t = seq(0, npi, length.out=N);

2.) Implement the segments
	if(parts > 0) {
		tl = helix.link(n, parts);
		tt = tl$id / tl$div;
		seg = sinusoid(tt, (2*pi)*tl$id);
		attr(lst, "segments") = seg;
	}

3.) Formatting
	if(length(p2) > 1)
		stop("Provide either: length and slope, or the 2 endpoints!");

**Comment by Adi131313** [comment]
issue fixed
