### ISSUE TITLE
[new] Helper Function: circle.arc 

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#38]
# New Helper Function: circle.arc 

Generates the points on an arc of circle.

## R Code

	#' @export
	circle.arc = function(r=1, phi, center = c(0,0), N = 65) {
		id = seq(0, N-1) / N;
		dp = phi[2] - phi[1];
		dw = id * dp + phi[1];
		x  = r * cos(dw) + center[1];
		y  = r * sin(dw) + center[2];
		xy = list(x=x, y=y);
		return(xy);
	}

**Comment by Adi131313** [comment]
issue implemented
