### ISSUE TITLE
[new] Function drop.col

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#39]
# New Function drop.col

Some functions generate a data.frame with an additional id column. It is practical to drop the id column.

### Drop column
	#' @export
	drop.col = function(x, name) {
		id = match(name, names(x));
		isNA = is.na(id);
		if(any(isNA))
			warning("Names not found: ", paste0(name[isNA], collapse=", "));
		id = id[ ! isNA];
		if(length(id) == 0) return(x);
		return(x[, -id]);
	}

**Comment by Adi131313** [comment]
issue implemented
