### ISSUE TITLE
Implement Function to draw a Virus

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#4]
# VIrus Function

Implement basic function to draw a virus particle.

## Parameters

   virus = function(R = 1, center = c(0,0), n.spike = 10, off.spike = c(-0.1, 1),
      r.spike=0.25, phi.spike = 0, lwd = 1, lwd.spike = 2*lwd, col="#D06432") {
      \# TODO: implement code;
   }

- R = radius of particle;
- center = center coordinates of particle;
- n.spike = number of spikes;
- off.spike = offset of spikes relative to the large radius R;
- r.spike = radius of the circle on the tip of the spike;
- phi.spike = rotation of the spikes on the large circle;
- lwd.spike = line width of the spike;
- lwd = line width of large circle;

## DNA vs RNA
Additional parameters will be added later on:
- double helix (DNA) vs simple helix (RNA) vs curved helix;
- slope of the helix;
- number of helix-turns;
- colour of helix;
- lwd.helix = line width of helix;

**Comment by Adi131313** [comment]
TO DO:

Finish spikes

**Comment by discoleo** [comment]
- implemented;

TODO: genome will be integrated separately;
