### ISSUE TITLE
[new] Function to Generate the Terminal Axon

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#40]
# Terminal Axon

Function to generate the terminal axon: pre-synaptic part.

	## R Code
	
	# phi = angle of axon (in radians);
	# slope = slope of axon, as alternative to angle phi;
	# alpha = angle of tree-cone (in degrees);
	synapse = function(p, phi, type = c("Solid", "Tree", "Detail", "Radial"),
			slope=NULL, col=1, fill="#808080", l=1/2, n=4, alpha = 120,
			helix.scale = 1/12, ...) {
		type = match.arg(type);
		if( ! is.null(slope)) {
			th  = atan(slope);
			phi = alpha * pi / 360;
		} else {
			th  = phi;
			phi = alpha * pi / 360;
		}
		if(type == "Detail") {
			if(is.null(slope)) slope = tan(th);
			d  = if(phi >= 0) l else - l;
			cc = shiftPoint(p, d=d, slope=slope);
			th = th + pi + c(- phi, phi); # already 1/2;
			xy = circle.arc(r = l, th, center = cc);
			len = length(xy$x);
			p2 = c(xy$x[1], xy$y[1]);
			p1 = c(xy$x[len], xy$y[len]);
			lst = helix(p1, p2, n = n + 0.5, A = l * helix.scale, phi=0, N=129);
			lst = lst[[1]];
			lst$x = c(xy$x, lst$x);
			lst$y = c(xy$y, lst$y);
			lst$col = col; lst$fill = fill;
			class(lst) = c("polygon", "list")
			lst = list(lst);
			return(as.bioshape(lst));
		}
		# Tree Types
		if(phi >= 0) {
			th = th + c(- phi, phi);
		} else {
			th = th + pi + c(- phi, phi);
		}
		if(type == "Tree") {
			px = l * cos(th) + p[1];
			py = l * sin(th) + p[2];
			id = seq(0, 1, length.out = n);
			px = id * px[1] + (1 - id) *  px[2];
			py = id * py[1] + (1 - id) *  py[2];
			xy = data.frame(x = p[1], y = p[2], id = seq(n));
			xy = rbind(xy, data.frame(x = px, y = py, id = seq(n)));
		} else if(type == "Radial") {
			id = seq(th[1], th[2], length.out = n);
			px = l * cos(id) + p[1];
			py = l * sin(id) + p[2];
			xy = data.frame(x = p[1], y = p[2], id = seq(n));
			xy = rbind(xy, data.frame(x = px, y = py, id = seq(n)));
		} else if(type == "Solid") {
			px = l * cos(th) + p[1];
			py = l * sin(th) + p[2];
			xy = list(x = c(p[1], px), y = c(p[2], py), col=col, fill=fill);
			class(xy) = c("polygon", "list");
		} else stop("Not yet implemented!");
		xy = as.bioshape(list(xy));
		return(xy);
	}

**Comment by discoleo** [comment]
## Examples

Note: the function is **NOT** yet integrated into the neuron function!

	### Synapse
	plot.base()
	tmp = neuron(c(0,2), phi=pi/6)
	lines(tmp)
	lines(synapse(c(tmp[[6]]$x[2], tmp[[6]]$y[2]), slope=tan(pi/6), type="D", l=0.8, alpha=160))
	
	###
	plot.base()
	tmp = neuron(c(0,2), phi=pi/6)
	lines(tmp)
	lines(synapse(c(tmp[[6]]$x[2], tmp[[6]]$y[2]), slope=tan(pi/6)))

**Comment by Adi131313** [comment]
issue implemented
