### ISSUE TITLE
Draw spikes using circles

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#42]
# Draw spikes using circles

Draw a circle, if ngon.spike = 0;

## R Code

	# off.spike = starting & ending of the spike;
	#' @export
	spikes = function(R = 1, center = c(0,0), n.spike = 10, off.spike = c(0, 1),
 	                r.spike=0.25, ngon.spike=4, phi.spike = 0, lwd = 1, lwd.spike = 2*lwd,
  	               col = "#D06432", fill = NULL) {
		# TODO: rename to r.ngon;
		r.ngon = r.spike;
		### Spikes
		c1 = pointsCircle(n.spike, r = R + off.spike[1], center = center, phi = phi.spike);
		c2 = pointsCircle(n.spike, r = R + off.spike[2], center = center, phi = phi.spike);
		spike = lapply(seq(n.spike), function(id) {
			list(x = c(c1$x[id], c2$x[id]), y = c(c1$y[id], c2$y[id]));
		});
		spike$lwd = lwd.spike;
		spike$col = col;
		class(spike) = c("lines.list", "list");
		virus = list(spike);
		### Head of Spikes
		if( ! is.null(r.ngon) && r.ngon > 0 ) {
			R3 = R + off.spike[2] + r.ngon;
			if(ngon.spike > 0) {
				h = ngon.circle(ngon.spike, N = n.spike, r = r.ngon, R = R3,
					center = center, phi = phi.spike, fill = fill);
				virus$head = h;
			} else {
				cc = pointsCircle(n.spike, r = R3,
					center = center, phi = phi.spike);
				cc = cbind(x = cc$x, y = cc$y);
				h  = list(r = r.ngon, center = cc,
					lwd = lwd, col = col, fill = fill);
				class(h) = c("circle", "list");
				virus$head = h;
			}
		}
		class(virus) = c("bioshape", "list");
		return(invisible(virus));
	}

**Comment by Adi131313** [comment]
issue implemented
