### ISSUE TITLE
Intersections of 2 Sine Functions

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#43]
# Intersections of 2 Sine Functions

Identify the intersections of 2 sine-functions:
- will be useful to draw links between the 2 strands of the DNA;

## R Code

	# Intersection of 2 shifted-Sine Functions
	which.intersect.sin = function(phi, n, from=0, to = n-1) {
		phi.eq = pi*(c(1,3) - sum(phi))/2;
		id.neg = which(phi.eq < 0);
		if(length(id.neg) > 0) {
			shift = abs(floor(phi.eq[id.neg] / (2*pi)));
			phi.eq[id.neg] = phi.eq[id.neg] + (2*pi)*shift;
		}
		x0 = sapply(seq(from, to), function(n) {
			phi.eq + 2*n*pi;
		})
		x0 = sort(x0);
		x1 = x0 + phi[1]*pi;
		# x1 = non-shifted; x2 = shifted;
		return(list(x0 = x0, x1=x1));
	}

## Test

	phi = c(0.7, 1.5)
	curve(sin(x + phi[1]*pi), -2*pi, 6*pi)
	curve(sin(x + phi[2]*pi), add = T, col="red")
	pp = which.intersect.sin(phi, 3)
	abline(v = pp$x0, col="blue")
	points(pp$x0, sin(pp$x1), col="green")

**Comment by Adi131313** [comment]
issue implemented
