### ISSUE TITLE
BUG: Vertical synapses

### ISSUE THREAD

**Issue by Adi131313** [Adi131313/BioShapes#44]
Arrow points at wrong direction

**Comment by discoleo** [comment]
Updated code for function neuron():
- *rounds* the slope to Inf for angles close to pi/2 and 3*pi/2;
- corrects the slope to negative for axons between pi and 2*pi;

## R Code

	### Axon
	if(axon.length != 0) {
		phiA  = phiR[n];
		slope = if(abs(phiA - pi20) < 1E-2 || abs(phiA - pi32) < 1E-2) Inf
			else tan(phiA);
		xy = shiftPoint(c(x0[n], y0[n]), d = sg[n] * axon.length, slope = slope);
		axon = list(x = c(x0[n], xy[1]), y = c(y0[n], xy[2]));
		axon = list(axon);
		lenDendites = n - 1;
		if( ! is.null(type.syn)) {
			syn  = synapse(xy, slope = sg[n] * slope, type = type.syn);
			axon = c(axon, syn);
		}

**Comment by discoleo** [comment]
The synapse function contains a bug as well. The case type == "Detail" needs to be updated.

	if(type == "Detail") {
		if(is.null(slope)) slope = tan(th);
		sg = th > pi/2 & th <= 3*pi/2;
		d  = if(sg) -l else l;
		cc = shiftPoint(p, d = d, slope=slope);
		th = th + pi + c(- phi, phi); # already 1/2;
		xy = circle.arc(r = l, th, center = cc);

**Comment by discoleo** [comment]
## Test

	### Test Neuron Synapses
	plot.neuron = function(p, phi, type, dphi = c(0, -pi/9, pi/9)) {
		for(dp in dphi) {
			tmp = neuron(p, phi= phi + dp, type=type);
			lines(tmp);
		}
	}
	
	type = "Detail"
	plot.base(ylim = c(-10, 10))
	plot.neuron(c(4,8), phi = -pi/2, type=type)
	plot.neuron(c(8,4), phi = pi, type=type)
	plot.neuron(c(4,-8), phi = pi/2, type=type)
	plot.neuron(c(0,-4), phi = 0, type=type)

**Comment by Adi131313** [comment]
issue fixed
