### ISSUE TITLE
[Bug] Function which.intersect.sin: angles

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#47]
# Function which.intersect.sin

It is more useful to have the angles in radians:
- they were initially in rad / pi, but this is impractical inside other functions;
- reverting back to full radians;

## R Code

Two lines of code will change slightly:
> phi.eq = (pi*c(1,3) - sum(phi))/2;\
> ...\
> x1 = x0 + phi[1];

The following line is also need - will discuss it:
> if(to - floor(to) >= 0.5) x0 = c(x0, x0[length(x0)] + pi);

The tests will need to be updated as well:

	# TODO: Example showing design of DNA
	# Intersection of sine functions
	phi = c(0.7, 1.5) * pi;
	curve(sin(x + phi[1]), -2*pi, 6*pi)
	curve(sin(x + phi[2]), add = T, col="red")
	pp = which.intersect.sin(phi, 3)
	abline(v = pp$x0, col="blue")
	points(pp$x0, sin(pp$x1), col="green")

**Comment by Adi131313** [comment]
issue fixed
