### ISSUE TITLE
Function to draw a Star Shape

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#5]
# Star Shape

Implement a function to generate a star-like shape.

## Function Arguments

   star = function(n, R = c(2,1), center = c(0,0), lwd=1, phi = pi/2, col=1) {
      \# TODO: implement code;
   }

- n = number of spikes of star;
- R = c(2,1): the outer & inner radius of the star;
- center = center of star;
- lwd = line width;
- phi = rotation of star;
- col = colour;

## R Code
- generate n radial point on circle with radius R[1] and phi = phi;
- generate n radial points on circle with radius R[2] and phi = phi + pi;
- unite alternatively the points using a line;

**Comment by Adi131313** [comment]
issue fixed
