### ISSUE TITLE
[Enhance] Plotting of circle.arc

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#50]
# Enhance the Plotting of circle.arc

In function lines.object.base:
- Use/Initialize argument lwd inside the circle.arc code;

## R Code

	# in } else if(inherits(lst, "circle.arc")) {
	col = if(is.null(lst$col)) col else lst$col;
	lwd = if(is.null(lst$lwd)) lwd else lst$lwd;

**Comment by Adi131313** [comment]
issue fixed
