### ISSUE TITLE
New Function: genome

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#51]
# New Function: genome

## R Code

	genome = function(r, center = c(0,0), phi.dna = pi/4,
				type = c("DNA", "helix", "arc", "circle", "cDNA", "css", "line", "none"),
				lwd=2, col = "#64D000", ...) {
		type = match.arg(type);
		if(type == "none") return(NULL);
		as.xy = function() {
			p1x = r * cos(phi.dna) + center[1];
			p1y = r * sin(phi.dna) + center[2];
			# p1  = c(p1x, p1y);
			p2x = r * cos(phi.dna + pi) + center[1];
			p2y = r * sin(phi.dna + pi) + center[2];
			# p2  = c(p2x, p2y);
			return(list(x = c(p2x, p1x), y = c(p2y, p1y)));
		}
		if(type == "DNA") {
			p = as.xy();
			# TODO: add lwd
			lst = dna.new(p$x, p$y, ...);
			return(invisible(lst));
		}
		if(type == "helix") {
			p = as.xy();
			lst = helix(p$x, p$y, ...);
			return(invisible(lst));
		}
		if(type == "arc") {
			# TODO: parameter;
			phi.arc = c(pi/6, 2*pi - pi/6);
			lst = list(r = r, center = center, phi = phi.arc, lwd=lwd, col=col);
			class(lst) = c("circle.arc", "list");
			return(as.bioshape(list(lst)));
		}
		if(type == "circle") {
			lst = list(r = r, center = center, lwd=lwd, col=col);
			class(lst) = c("circle", "list");
			return(as.bioshape(list(lst)));
		}
		if(type == "line") {
			p = as.xy();
			p$lwd = lwd; p$col = col;
			return(as.bioshape(list(p)));
		}
		if(type == "helix") {
			# TODO
		}
	}

**Comment by discoleo** [comment]
# Examples

	cc = c(4,5); r = 3;
	plot.base()
	lines(virus(r, cc))
	lst = genome(r * 0.75, cc)
	lines(lst)
	
	### Circle Arc
	cc = c(4,5); r = 3;
	plot.base()
	lines(virus(r, cc))
	lst = genome(r * 0.75, cc, type = "arc")
	lines(lst)
	
	### Circle
	cc = c(4,5); r = 3;
	plot.base()
	lines(virus(r, cc))
	lst = genome(r * 0.5, cc, type = "circle")
	lines(lst)

**Comment by Adi131313** [comment]
issue implemented
