### ISSUE TITLE
[Enhance] Helix: add args lwd & col

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#53]
# Function helix: args lwd & col

- add the arguments lwd & col;

## R Code

- add arguments to function (after slope arg):
> lwd = NULL, col = NULL

- insert code at aprox. line 88 and before line: lst = list(lst);

	lst = sinusoid(t*ninv, t);
	if( ! is.null(lwd)) lst$lwd = lwd;
	if( ! is.null(col)) lst$col = col;
	lst = list(lst);

**Comment by discoleo** [comment]
## Function dna.new

Add also arg col to this function:

## R Code

	dna.new = function(x, y, n=3, phi=c(pi/2, pi) + pi/4, A=1, n.lines = 6,
			lwd=1, col = c("red", "green"), col.lines = col) {
		p1 = c(x[1], y[1]); p2 = c(x[2], y[2]);
		h1 = helix(p1, p2, n=n, A=A, phi=phi[1], lwd=lwd, parts=0);
		h2 = helix(p1, p2, n=n, A=A, phi=phi[2], lwd=lwd, parts=0);
		# TODO: use helix();

The line if( ! is.null(... )) remains the same. There is only a TODO for the future.

**Comment by Adi131313** [comment]
issue implemented
