### ISSUE TITLE
[Enhance] Function virus2: all spike offsets are adjustable

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#54]
# function virus2: Spike Enhancements

- all 3 offsets are now adjustable;
- color args: have been refactored;

## R Code

	virus2 = function(R = 2, center = c(0,0), n.spike = 10, off.spike = c(0, 1, 1.5),
			r.spike=0.25, ngon.spike=c(4, 0), phi.spike = 0,
			lwd = 8, lwd.spike = lwd/2, col = "#D06432",
			col.spike = c("#c90e40", "red"),
			fill.spike = c("#5128c9", "yellow")) {
		
		v1 = virus(R = R, center = center, n.spike = n.spike, off.spike = off.spike,
		r.spike=r.spike, ngon.spike = ngon.spike[1], phi.spike = phi.spike,
			lwd = lwd, lwd.spike = lwd.spike[1],
			col = col, col.spike = col.spike[1], fill.spike = fill.spike[1])
		
		### Spikes
		if(length(lwd.spike) <= 1) lwd.spike = rep(lwd.spike[1], 2);
		off.spike0 = off.spike[1];
		off.spike_i = c(off.spike0, off.spike[3]);
		spikes2 = spikes(R = R, center = center, n.spike = n.spike,
			off.spike = off.spike_i, r.spike=r.spike,
			ngon.spike = ngon.spike[2], phi.spike = phi.spike + pi/n.spike,
			lwd = lwd.spike[2], lwd.spike = lwd.spike[2],
			col = col.spike[2], fill = fill.spike[2]);
		
		virus = c(spikes2, v1);
		virus = as.bioshape(virus);
		return(virus)
	}

**Comment by Adi131313** [comment]
issue fixed
