### ISSUE TITLE
[Enhance] Helix.rad: add args lwd, col & fill

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#55]
# Function helix.rad: args lwd, col & fill

- add the arguments lwd, col; & fill

## R Code

- aprox. line 111 and before line: class(xy) = ...;

	xy = list(x=x, y=y);
	if( ! is.null(lwd)) xy$lwd = lwd;
	if( ! is.null(col)) xy$col = col;
	if( ! is.null(fill)) xy$fill = fill;
	class(xy) = c("polygon", "list");

**Comment by Adi131313** [comment]
issue fixed
