### ISSUE TITLE
[Enhance] lines.object.base: add lwd arg for polygons

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#56]
# Function lines:object.base: add lwd arg for polygons

## R Code
- around line 108 and before the call to polygon(...);

	} else if(inherits(lst, "polygon")) {
		# if(is.null(fill)) fill = lst$fill;
		lwd = if(is.null(lst$lwd)) lwd else lst$lwd;
		col = if(is.null(lst$col)) col else lst$col;
		fill = lst$fill;

**Comment by Adi131313** [comment]
issue fixed
