### ISSUE TITLE
Function to draw Convex Lens

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#6]
# Convex Lens

Implement a function to generate a convex lens.

## Function Arguments

   lens = function(x, y, R = NULL, scale = c(1,1), lwd=1, col=1) {
   \# TODO: implement code;
   }

- x, y = x and y coordinates of the 2 outer margins of the lens;
- R = the 2 radii of the lens;
- scale = the scaling factor of the 2 radii;

### Step 1: Compute Radius
If the radius is NULL, then we will use the distance between the 2 margins.
   if(is.null(R)) {
      R = sqrt((x[2] - x[1])^2 + (y[2] - y[1])^2);
      R = c(R, R);
   } else if(length(R) == 1) R = c(R, R);
   R = R * scale;

### Step 2: Compute 2 Centers
   mid.x = (x[1] + x[2]) / 2;
   mid.y = (y[1] + y[2]) / 2;
   \# Compute actual centers of circles

### Step 3: Shift Points

Function shiftLine can shift also points orthogonal to a line:
	pp = shiftLine(x, y, slope = slope_of_line, d = d1);
	# where d1 = sqrt(R1^2 - d^2/4);
	# and d = sqrt((x[2] - x[1])^2 + (y[2] - y[1])^2); # TODO: sign + / -;

**Comment by Adi131313** [comment]
TODO: Generate and draw Circle segments

**Comment by Adi131313** [comment]
TODO: Generate and draw Circle segments

**Comment by Adi131313** [comment]
issue fixed
