### ISSUE TITLE
Rename function compute_slope to slope

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#7]
# Function compute_slope

Rename this function (in Graphic.Helper.R) to "slope". The old function will be marked as deprecated.

   compute_slope = function(x, y) {
      warning("Deprecated!";
      return(slope(x, y));
   }
  \# New name:
   slope = function(x, y) {
   \# old code remains ...
   }

**Comment by Adi131313** [comment]
issue fixed
