### ISSUE TITLE
[Bug] lines.object.base: syntax error

### ISSUE THREAD

**Issue by discoleo** [Adi131313/BioShapes#8]
# Bug in function lines.object.base

There is a syntax error in the function lines.object.base (in file Graphic.Helper.Plot.R).

In the main else clause: there is a missing assignment:
	lst$lwd = NULL; lst$col = \# MISSING value!
	# should be:
	lst$lwd = NULL; lst$col = NULL;

**Comment by Adi131313** [comment]
issue fixed
